### ISSUE TITLE
glue-0.1.1.0 can't compile its test suite

### ISSUE THREAD

**Issue by peti** [seanparsons/glue#2]
Citing from http://hydra.cryp.to/build/947718/log/raw:

```
Preprocessing test suite 'tests' for glue-0.1.1.0...

test/Main.hs:4:18:
    Could not find module ‘Spec’
    Use -v to see a list of the files searched for.
```

**Comment by seanparsons** [comment]
Works for me and Travis: https://travis-ci.org/seanparsons/glue/jobs/68496505

**Comment by seanparsons** [comment]
The test specific dependencies even appear to be the same, so this looks more like a Nix specific issue to me, is there a way of seeing the command line calls (with parameters) that cabal is invoked with?

**Comment by peti** [comment]
Try running the tests from a release tarball from Hackage. I'm pretty sure the module is missing.

**Comment by seanparsons** [comment]
@peti I thought that was what the very last command did in the Travis Multi GHC script.

**Comment by seanparsons** [comment]
Aha, I see it just includes test/Main.hs and nothing else. This makes me so grumpy with cabal!

**Comment by peti** [comment]
That last line in the Travis configuration does not try to build the test suite.

**Comment by seanparsons** [comment]
Indeed.

**Comment by seanparsons** [comment]
This should be sorted with 0.1.1.1 that I've just pushed.
